spring:
  application:
    name: city-service
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
      host: localhost
      port: 8500
    config:
      server:
        bootstrap: true
      uri: http://config_host:${config.port:8888}
      fail-fast: true